hw04_struct_comparator
shatilovlex/golang_home_work_basic pull request #3
Opened 2024-10-30 19:55 UTC by shatilovlex

2024-10-30 20:06 UTC, vladislavmass requested changes

2024-10-30 20:06 UTC, hungry-honeybadger commented on hw04_struct_comparator/types/book.go
> +func (b Book) ID() int {
В go принято что бы у всех методов одной структуры был одинаковый ресивер. Либо по значению либо по указателю, но так как у нас часть методов меняют значения полей, то все ресивера должны быть по указателю

2024-10-30 23:23 UTC, shatilovlex commented on hw04_struct_comparator/types/book.go
> +func (b Book) ID() int {
> В go принято что бы у всех методов одной структуры был одинаковый ресивер. Либо по значению либо по указателю, но так как у нас часть методов меняют значения полей, то все ресивера должны быть по указателю

Спасибо за коммент, исправил.

2024-11-01 05:51 UTC, vladislavmass approved these changes

2024-11-01 09:01 UTC, merged